name: 🐞 Bug Report
description: 버그를 발견했을 때 사용하세요
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 버그 리포트
        발견한 버그에 대해 자세히 설명해주세요.
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 버그가 무엇인지 간략하게 설명해주세요.
      placeholder: 여기에 설명을 작성해주세요
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 재현 방법
      description: 버그를 재현하는 방법을 단계별로 설명해주세요.
      placeholder: |
        1. '...'을 실행합니다
        2. '...'을 클릭합니다
        3. '...' 결과를 확인합니다
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 예상되는 동작
      description: 기대했던 결과를 설명해주세요.
      placeholder: 여기에 작성해주세요
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: 환경 정보
      description: 실행 환경을 적어주세요 (예: OS, Java 버전, etc.)
      placeholder: "예: macOS, Java 17, Spring Boot 3.1.2"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷 (선택)
      description: 필요하면 스크린샷을 첨부해주세요.
      placeholder: 스크린샷이나 로그를 여기에 붙여넣어 주세요.
  - type: textarea
    id: additional-info
    attributes:
      label: 추가 정보
      description: 버그와 관련된 추가 정보를 제공해주세요 (옵션).
